services:
  postgres:
    image: postgres:18.4-alpine
    container_name: ff-codex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ff-codex
      POSTGRES_PASSWORD: ff-codex
      POSTGRES_DB: ff-codex-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ff-codex -d ff-codex-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ff-codex-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
  migrate:
    image: nxyt/sqlx-cli
    depends_on:
      postgres:
       condition: service_healthy
    command: sqlx migrate run
    volumes:
      - ./migrations:/migrations
    environment:
      - DATABASE_URL=postgres://ff-codex:ff-codex@postgres:5432/ff-codex-db?sslmode=disable
    networks:
      - ff-codex-net
networks:
  ff-codex-net:
    driver: bridge
volumes:
  postgres_data: